baseURL = "https://hugsch.github.io/"
languageCode = "en-us"
title = "hugsch"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength = 9

[Params]
dateFormat = "02-01-2006"
comments = false
readingTime = true
wordCount = false
useHLJS = false
socialShare = true
delayDisqus = true
showRelatedPosts = true
gcse = false
Lastmod = true
rss = false
pagination = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[author]
name = "hugsch"
mastodon = "@husch@fosstodon.org"

[[menu.main]]
name = "Home"
url = "/"
weight = 5

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archives/"
weight = 30
