baseURL: https://hugsch.github.io/
languageCode: en-us
title: hugsch
theme: "PaperMod"

params:
    homeInfoParams:
        Title: List of my most recent blog posts!
        Content: 

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/hugsch"
        - name: "Mastodon"
          url: "https://fosstodon.org/@husch"
    ShowReadingTime: true
    author: "hugsch"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20