baseURL: https://hugsch.github.io/
languageCode: en-us
title: hugsch
theme: "lightbi-hugo"
#googleAnalytics: "XXX"
enableRobotsTXT: true
enableGitInfo: false
Paginate: 6

Params:
  dateFormat: 02-01-2006
  comments: false
  readingTime: true
  wordCount: false
  useHLJS: false
  socialShare: true
  delayDisqus: true
  showRelatedPosts: true 
  summaryLength: 9
  gcse: false
  Lastmod: true
  rss: false 
  pagination: 10

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

author:
  name: hugsch
  mastodon: "@husch@fosstodon.org"


menu:
    main:
        - identifier:
          name: Home
          url: /
          weight: 5
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 30